package org.foo.controller;

import com.ajaxjs.dataservice.model.UrlGroup;
import com.ajaxjs.sqlman.Action;
import com.ajaxjs.sqlman.JdbcConnection;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.Statement;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class TreeNodeAdminControllerTest {
    private TreeNodeAdminController controller;

    @BeforeEach
    void setUp() throws Exception {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:tree_node_admin;MODE=MySQL;DATABASE_TO_UPPER=FALSE;DB_CLOSE_DELAY=-1");
        Connection connection = dataSource.getConnection();
        JdbcConnection.setConnection(connection);

        try (Statement statement = connection.createStatement()) {
            statement.execute("DROP TABLE IF EXISTS ds_url_group");
            statement.execute("CREATE TABLE ds_url_group ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "name VARCHAR(50) NOT NULL, parent_id BIGINT NOT NULL, sort_no INT, "
                    + "creator VARCHAR(50), creator_id BIGINT, create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP)");
            statement.execute("INSERT INTO ds_url_group (id, name, parent_id, sort_no) VALUES "
                    + "(1, 'root', -1, 1), (2, 'child', 1, 1), (3, 'grandchild', 2, 1), (4, 'sibling', 1, 2)");
        }

        controller = new TreeNodeAdminController();
    }

    @AfterEach
    void tearDown() {
        JdbcConnection.closeConnection();
    }

    @Test
    void createAndListBuildsNestedTree() {
        assertTrue(controller.create(node("new child", 4L)));

        assertEquals(1L, count("SELECT COUNT(*) FROM ds_url_group WHERE name = ?", "new child"));

        List<Map<String, Object>> roots = controller.list(-1L, 3L);
        Map<String, Object> root = roots.get(0);
        Map<String, Object> child = child(root, 2L);
        Map<String, Object> grandchild = child(child, 3L);

        assertEquals("root", root.get("title"));
        assertEquals(true, grandchild.get("selected"));
        assertEquals(false, child.get("selected"));
    }

    @Test
    void updateMovesNodeToExistingParentAndRejectsInvalidMoves() {
        assertTrue(controller.update(node("child moved", 4L), 2L));
        assertEquals(4L, new Action("SELECT parent_id FROM ds_url_group WHERE id = ?").query(2L).one(Long.class));

        assertThrows(IllegalArgumentException.class, () -> controller.update(node("self", 2L), 2L));
        assertThrows(IllegalArgumentException.class, () -> controller.update(node("cycle", 3L), 1L));
        assertThrows(IllegalArgumentException.class, () -> controller.update(node("missing", 99L), 4L));
    }

    @Test
    void deleteProtectsNonLeafUnlessSubtreeDeletionIsRequested() {
        assertFalse(controller.delete(2L, false));
        assertTrue(controller.delete(2L, true));

        assertEquals(0L, count("SELECT COUNT(*) FROM ds_url_group WHERE id IN (?, ?)", 2L, 3L));
        assertEquals(1L, count("SELECT COUNT(*) FROM ds_url_group WHERE id = ?", 4L));
    }

    private UrlGroup node(String name, Long parentId) {
        UrlGroup node = new UrlGroup();
        node.setName(name);
        node.setParentId(parentId);
        return node;
    }

    private long count(String sql, Object... params) {
        Long count = new Action(sql).query(params).one(Long.class);

        return count;
    }

    @SuppressWarnings("unchecked")
    private Map<String, Object> child(Map<String, Object> parent, Long id) {
        List<Map<String, Object>> children = (List<Map<String, Object>>) parent.get("children");

        return children.stream()
                .filter(item -> id.equals(((Number) item.get("id")).longValue()))
                .findFirst()
                .orElseThrow(() -> new AssertionError("Expected child node: " + id));
    }
}
