<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.ajaxjs</groupId>
        <artifactId>ajaxjs-cms</artifactId>
        <version>1.0.6</version>
        <relativePath/>
    </parent>

    <artifactId>aj-data-service</artifactId>
    <name>aj-dataservice</name>
    <version>1.3</version>
    <packaging>jar</packaging>
    <description>Minimal requirements for the component of Spring Framework</description>
    <url>https://aj-docs.ajaxjs.com/</url>

    <scm>
        <url>https://github.com/lightweight-component/aj-framework/tree/master/aj-spring</url>
        <connection>scm:git:https://github.com/lightweight-component/aj-framework.git</connection>
    </scm>

    <issueManagement>
        <system>Github Issues</system>
        <url>https://github.com/lightweight-component/aj-framework/issues</url>
    </issueManagement>

    <dependencies>
        <!--  Spring  -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <scope>provided</scope>
        </dependency>

        <!--  Spring 测试  -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
        </dependency>

        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.ajaxjs</groupId>
            <artifactId>base</artifactId>
            <version>1.4</version>
        </dependency>
    </dependencies>
</project>