package com.ajaxjs.dataservice.datasource;

import com.ajaxjs.sqlman.Action;
import com.ajaxjs.sqlman.JdbcConnection;
import com.ajaxjs.sqlman.model.DatabaseVendor;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.Statement;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class TestDatasourceService {
    Connection connection;

    DatasourceService service;

    @BeforeEach
    void setUp() throws Exception {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:datasource_service;DB_CLOSE_DELAY=-1");
        connection = dataSource.getConnection();
        JdbcConnection.setConnection(connection);

        try (Statement statement = connection.createStatement()) {
            statement.execute("DROP TABLE IF EXISTS ds_datasource");
            statement.execute("CREATE TABLE ds_datasource ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "name VARCHAR(45) NOT NULL, url_dir VARCHAR(50) NOT NULL UNIQUE, "
                    + "type VARCHAR(50) NOT NULL DEFAULT '', url VARCHAR(255) NOT NULL, "
                    + "username VARCHAR(255), password VARCHAR(255), connect_ok BOOLEAN, "
                    + "stat TINYINT NOT NULL DEFAULT 0, cross_db BOOLEAN, uid BIGINT, "
                    + "create_date TIMESTAMP, update_date TIMESTAMP)");
        }

        service = new DatasourceService();
    }

    @AfterEach
    void tearDown() {
        JdbcConnection.closeDb();
    }

    @Test
    void createAndListPersistDatasourceWithoutReturningPassword() {
        long id = service.create(dataSource("main", "jdbc:h2:mem:datasource_target;DB_CLOSE_DELAY=-1"));

        List<DataSourceInfo> list = service.list();

        assertEquals(1L, id);
        assertEquals(1, list.size());
        assertEquals("main", list.get(0).getUrlDir());
        assertNull(list.get(0).getPassword());
    }

    @Test
    void createRejectsDuplicatedUrlDir() {
        service.create(dataSource("main", "jdbc:h2:mem:first"));

        assertThrows(IllegalArgumentException.class, () -> service.create(dataSource("main", "jdbc:h2:mem:second")));
        assertThrows(IllegalArgumentException.class, () -> service.checkIfIsRepeat(null, null));
    }

    @Test
    void updateChangesDatasourceAndAllowsItsOwnUrlDir() {
        long id = service.create(dataSource("main", "jdbc:h2:mem:before"));
        DataSourceInfo changed = new DataSourceInfo();
        changed.setId(id);
        changed.setName("changed");
        changed.setUrlDir("main");

        assertTrue(service.update(changed));
        assertEquals("changed", new Action("SELECT name FROM ds_datasource WHERE id = ?").query(id).one(String.class));
        assertThrows(IllegalArgumentException.class, () -> service.update(new DataSourceInfo()));
    }

    @Test
    void deleteMarksActiveDatasourceAsDeleted() {
        long id = service.create(dataSource("main", "jdbc:h2:mem:delete"));

        assertTrue(service.delete(id));
        assertEquals(1, new Action("SELECT stat FROM ds_datasource WHERE id = ?").query(id).one(Integer.class));
        assertFalse(service.delete(id));
        assertTrue(service.list().isEmpty());
    }

    @Test
    void testAndGetConnectionUseStoredDatasourceConfiguration() throws Exception {
        long id = service.create(dataSource("target", "jdbc:h2:mem:datasource_target;DB_CLOSE_DELAY=-1"));

        assertTrue(service.test(id));
        try (Connection targetConnection = service.getConnectionByDataSourceId(id)) {
            assertNotNull(targetConnection);
            assertFalse(targetConnection.isClosed());
        }
    }

    @Test
    void getConnectionRejectsMissingDatasource() {
        assertThrows(IllegalArgumentException.class, () -> service.getConnectionByDataSourceId(1L));
        assertThrows(IllegalArgumentException.class, () -> service.getConnectionByDataSourceId(null));
    }

    @Test
    void tablePaginationRejectsInvalidBounds() {
        assertThrows(IllegalArgumentException.class, () -> service.getTableAndComment(1L, -1, 1, null, null));
        assertThrows(IllegalArgumentException.class, () -> service.getTableAndComment(1L, 0, 0, null, null));
        assertThrows(IllegalArgumentException.class, () -> service.getTableAndComment(1L, 0, 501, null, null));
    }

    @Test
    void getCommentFromCreateTableSqlParsesComment() {
        assertEquals("数据源", DatasourceService.getCommentFromCreateTableSql("CREATE TABLE ds_datasource COMMENT='数据源'"));
        assertNull(DatasourceService.getCommentFromCreateTableSql("CREATE TABLE ds_datasource"));
    }

    DataSourceInfo dataSource(String urlDir, String url) {
        DataSourceInfo dataSource = new DataSourceInfo();
        dataSource.setName("数据源");
        dataSource.setUrlDir(urlDir);
        dataSource.setType(DatabaseVendor.H2);
        dataSource.setUrl(url);
        dataSource.setUsername("sa");
        dataSource.setPassword("secret");
        dataSource.setCrossDb(false);

        return dataSource;
    }
}
